spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    include: secret
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true1
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          naver:
            scope:
            redirect-uri: https://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://localhost/login/oauth2/code/kakao
            client-authentication-method: POST
          google:
            redirect-uri: https://localhost/login/oauth2/code/google
            client-name: Google
            scope:
              - email
              - profile
          facebook:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-name: Facebook
            scope:
          instagram:
            provider: instagram
            scope: user_profile,user_media
            client-name: Instagram
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          instagram:
            authorization-uri: https://api.instagram.com/oauth/authorize
            token-uri: https://api.instagram.com/oauth/access_token
            user-info-uri: https://graph.instagram.com/me?fields=id,username&access_token={access-token}
            user-name-attribute: username

logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  instaMember:
    fromLikeablePeople:
      maxSize: 10
